/*
"Auto Attendance"
by eggbegg
on 2022-12-02

objects:
1 - type=function (doangle) "does a 90 or 180 degree angle"
2 - SCRAPPED FOR RHYTHM
3 - type=function (rhythm) "structures all of the movement"
4 - type=function (logall) "log all sensor values and books"
5 - type=function (fullstop) "stops the robot"
*/

#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int truedelay; // define truedelay
int val_delay = 13; // define degree delay value
int students = 0; // define books
int i; // define later i variable

void logall(){ // log every variable
	displayTextLine(0, "Auto Attendance", "");
	displayTextLine(1, "task_light=%d", SensorValue[S3]);
	displayTextLine(2, "task_sonar=%d", SensorValue[S4]);
	displayTextLine(4, "%d", students);
}

void compensatel(int speed){
	motor[motorB] = speed;
	motor[motorC] = -speed;
	delay(100);
}

void doangle(int speed, char* direction, int angle){ // main function for doing *close to exact* 90 and 180 degree turns
	if(direction == "l"){ // left turn
		motor[motorB] = speed;
		motor[motorC] = -speed;
		truedelay = (angle == 90) ? val_delay : val_delay * 2; // if angle is 90 set val_delay if not set value val_delay * 2
		delay(speed * truedelay); // attempt to get closest angle
	}
	else if(direction == "r"){ // right turn
		motor[motorB] = -speed;
		motor[motorC] = speed;
		truedelay = (angle == 90) ? val_delay : val_delay * 2; // if angle is 90 set val_delay if not set value val_delay * 2
		delay(speed * truedelay); // attempt to get closest angle
	}
}

void domovement(char* direction, int speed) // main function for handling movement (not angles)
{
	if (direction	== "Straight") { // If it wants to go straight
		motor(motorB) = speed;
		motor(motorC) = speed;
	}
	else if (direction == "Back") { // If it wants go backwards
		motor(motorB) = -speed;
		motor(motorC) = -speed;
	}
}

task main(){
	for (i=0;i<3;i++){ // repeat 3
		while(SensorValue[S3] > 14){
			logall();
			domovement("Straight", 50); 
		}
		displayTextLine(6, "Line Found!"); // display line found
		doangle(50, "r", 90); // 90 degree turn
		while(SensorValue[S3] > 14){
			logall();
			domovement("Straight", 50); 
		}

		if (SensorValue[S4] < 20) {
			students = students+1;
			logall();
		}
		doangle(50, "r", 180); // 180 degree turn
		while(SensorValue[S3] > 14) {
			logall();
			domovement("Straight", 50);
		}
		compensatel(50);

		if (SensorValue[S4] < 27) {
			students = students+1;
			logall();
		}
		domovement("Back", 50);
		delay(1000);
		doangle(50, "r", 90); // 90 degree turn
	}
	doangle(50, "r", 180); // 180 degree turn
	domovement("Straight", 50);
	delay(5000);
	logall();
}
