#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void action(char* direction, int speed, int del, bool angle){
    if (direction == "r"){
        motor[motorB] = -speed;
        motor[motorC] = speed;
    }
    else if (direction == "l"){
        motor[motorB] = -speed;
        motor[motorC] = speed;
    }
    else if (direction == "s"){
        motor[motorB] = speed;
        motor[motorC] = speed;
    }
    else if (direction == "b"){
        motor[motorB] = -speed;
        motor[motorC] = -speed;
    }
    
    if (angle == true){
        delay(del * 3.55); // placeholder
    }
    else if (angle == false){
        delay(del);
    }
}

task main(){
    action("s", 50, 1000, false);
    delay(200);
    action("r", 50, 180, true);
}
