#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int i;
	int isTouching = SensorValue[S1];
	
	for (i=0;i<20;i++) {
		while (isTouching == 0) {
			isTouching = SensorValue[S1];
			motor[motorB] = 50;
			motor[motorC] = 50;
			delay(100);
		}
		
		motor[motorB] = -50;
		motor[motorC] = -50;
		
		delay(250);
		
		motor[motorB] = -50;
		motor[motorC] = 50;
		delay((2580/360) * 90);
		isTouching = 0;
	}
}
